language: julia
os:
  - linux
  - osx
julia:
  - 1.0 
  - nightly
notifications:
  email: false
sudo: false
matrix:
  allow_failures:
  - julia: nightly
before_install:
    - if [ `uname` = "Linux" ]; then
        sudo apt-get update -qq -y;
        sudo apt-get install -y libcairo2 libfontconfig1 libpango1.0-0 libpng12-0 libpng12-dev libpixman-1-0 gettext;
      fi
after_success:
   - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
